import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/profile.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import TransitionEffect from "@/components/TransitionEffect";

export default function Home() {
  return (
    <>
      <Head>
        <title>Fatin Nooraina</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-center w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              <Image
                src={profilePic}
                alt="FatinNooraina"
                className="w-full h-auto lg:hidden md:inline-block md:w-full"
                priority
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50px, 50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="Turning Vision Into Reality With Code."
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                I am a self-taught fullstack developer with a Bachelor degree in
                Mechatronics Engineering. I have always found coding intuitive
                and have pushed myself to learn most effective ways to achieve a
                result. I am a fast learner and can quickly integrate into a
                team so I can provide value to the company and customers.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center gap-4">
                <Link
                  href="/CV-FatinNooraina.pdf"
                  target="_blank"
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg 
                  font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent 
                  hover:border-dark dark:bg-light dark:text-dark dark:hover:bg-dark dark:hover:text-light dark:hover:border-light
                  md:p-2 md:px-4 md:text-base"
                >
                  Resume
                </Link>
                <Link
                  href="mailto:fatinnooraina@gmail.com"
                  className="flex items-center text-dark dark:text-light p-2.5 px-6 rounded-lg text-lg 
                  font-semibold hover:border-dark border-2 dark:hover:border-light border-dark border-solid 
                  border-transparent md:text-base"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
